[package]
name = "derivation"
version = "0.1.0"
edition = "2021"

[dependencies]
core = {path = "../core"}
client = {path = "../client"}
ethers-core = "1.0.2"
eyre = "0.6.8"
flate2 = "1.0.25"
hex-literal = "0.4.1"
