name: cargo command

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: Swatinem/rust-cache@v2
      - run: ${{ inputs.command }}