name: test

on:
  push:
    branches:
        - master
  pull_request:

jobs:
  check:
    uses: ./.github/workflows/cargo.yml
    with:
      command: cargo check --all

  test:
    uses: ./.github/workflows/cargo.yml
    with:
      command: cargo test --all

  build:
    uses: ./.github/workflows/cargo.yml
    with:
      command: cargo build --all

  fmt:
    uses: ./.github/workflows/cargo.yml
    with:
      command: cargo fmt --all -- --check

  clippy:
    uses: ./.github/workflows/cargo.yml
    with:
      command: cargo clippy --all -- -D warnings
